apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: streaming-dataplane-foo-ingress
  annotations:
    github.com/project-slug: celonis/foo-ingress
    github.com/team-slug: celonis/developer-experience
    backstage.io/techdocs-ref: dir:.
    backstage.io/kubernetes-namespace: default
    backstage.io/kubernetes-label-selector: "app-selector=streaming-dataplane-foo-ingress"
    backstage.io/kubernetes-id: streaming-dataplane-foo-ingress
    argocd/app-name: streaming-dataplane-foo-ingress
  links:
    - url: https://example.com/?q=brokenImage
      title: brokenImage
      icon: brokenImage
    - url: https://example.com/?q=catalog
      title: catalog
      icon: catalog
    - url: https://example.com/?q=chat
      title: chat
      icon: chat
    - url: https://example.com/?q=dashboard
      title: dashboard
      icon: dashboard
    - url: https://example.com/?q=docs
      title: docs
      icon: docs
    - url: https://example.com/?q=email
      title: email
      icon: email
    - url: https://example.com/?q=github
      title: github
      icon: github
    - url: https://example.com/?q=group
      title: group
      icon: group
    - url: https://example.com/?q=help
      title: help
      icon: help
    - url: https://example.com/?q=user
      title: user
      icon: user
    - url: https://example.com/?q=warning
      title: warning
      icon: warning
    - url: https:/example/?q=adb
      title: adb
      icon: adb
    - url: https:/example/?q=add
      title: add
      icon: add
    - url: https:/example/?q=air
      title: air
      icon: air
    - url: https://github.cexample/?q=beach_access
      title: beach_access
      icon: beach_access
    - url: https:/example/?q=bed
      title: bed
      icon: bed
    - url: https://github.cexample/?q=bedroom_baby
      title: bedroom_baby
      icon: bedroom_baby
    - url: https://example/?q=cake
      title: cake
      icon: cake
    - url: https://githuexample/?q=calculate
      title: calculate
      icon: calculate
    - url: https://github.comexample/?q=detector_smoke
      title: detector_smoke
      icon: detector_smoke
    - url: https://github.com/example/?q=detector_status
      title: detector_status
      icon: detector_status
    - url: https://github.com/example/?q=developer_board
      title: developer_board
      icon: developer_board
    - url: https://githexample/?q=elevator
      title: elevator
      icon: elevator
    - url: https://githuexample/?q=fireplace
      title: fireplace
      icon: fireplace
    - url: https://githubexample/?q=first_page
      title: first_page
      icon: first_page
    - url: https://githubexample/?q=fit_screen
      title: fit_screen
      icon: fit_screen
    - url: https://giexample/?q=fitbit
      title: fitbit
      icon: fitbit
    - url: https://githubexample/?q=wind_power
      title: wind_power
      icon: wind_power
    - url: https://giexample/?q=window
      title: window
      icon: window
    - url: https://github.coexample/?q=window_closed
      title: window_closed
      icon: window_closed
    - url: https://github.example/?q=window_open
      title: window_open
      icon: window_open
    - url: https://github.coexample/?q=window_sensor
      title: window_sensor
      icon: window_sensor
    - url: https://githexample/?q=wine_bar
      title: wine_bar
      icon: wine_bar
    - url: https://gexample/?q=woman
      title: woman
      icon: woman
    - url: https://gitexample/?q=woman_2
      title: woman_2
      icon: woman_2
    - url: https://example/?q=work
      title: work
      icon: work
    - url: https://github.cexample/?q=work_history
      title: work_history
      icon: work_history
    - url: https://githexample/?q=work_off
      title: work_off
      icon: work_off
    - url: https://github.cexample/?q=work_outline
      title: work_outline
      icon: work_outline
    - url: https://github.com/ceexample/?q=workspace_premium
      title: workspace_premium
      icon: workspace_premium
    - url: https://githubexample/?q=workspaces
      title: workspaces
      icon: workspaces
    - url: https://github.com/ceexample/?q=workspaces_filled
      title: workspaces_filled
      icon: workspaces_filled
    - url: https://github.com/celexample/?q=workspaces_outline
      title: workspaces_outline
      icon: workspaces_outline
    - url: https://githuexample/?q=wrap_text
      title: wrap_text
      icon: wrap_text
    - url: https://github.comexample/?q=wrong_location
      title: wrong_location
      icon: wrong_location
    - url: https://gitexample/?q=wysiwyg
      title: wysiwyg
      icon: wysiwyg
    - url: https://example/?q=yard
      title: yard
      icon: yard
    - url: https://github.com/celonexample/?q=youtube_searched_for
      title: youtube_searched_for
      icon: youtube_searched_for
    - url: https://github.com/ceexample/?q=zone_person_alert
      title: zone_person_alert
      icon: zone_person_alert
    - url: https://github.com/cexample/?q=zone_person_idle
      title: zone_person_idle
      icon: zone_person_idle
    - url: https://github.com/celexample/?q=zone_person_urgent
      title: zone_person_urgent
      icon: zone_person_urgent
    - url: https://gitexample/?q=zoom_in
      title: zoom_in
      icon: zoom_in
    - url: https://github.example/?q=zoom_in_map
      title: zoom_in_map
      icon: zoom_in_map
    - url: https://githexample/?q=zoom_out
      title: zoom_out
      icon: zoom_out
spec:
  type: service
  owner: developer-experience
  lifecycle: experimental
  system: dataplane
  domain: streaming
